/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pop_up_formulir.java
 *
 * Created on Dec 14, 2012, 1:41:24 PM
 */
package PopUp;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.*;//JOptionePane
import java.awt.*;//Dimension
import java.util.*;
import java.awt.event.*;
import View.cekdata;
import panel.barang;
import View.Penjualan;
import View.selectdata;

/**
 *
 * @author akbar
 */
public class pop_up_barang extends javax.swing.JDialog {
    Dimension posisi;
    DefaultTableModel tabmod;
    int[] lebar = {100,110,110,110,110 };  //menyesuaikan lebar kolom
    cekdata cek = new cekdata();
    selectdata select = new selectdata();
    barang barang = new barang();
    Penjualan penjualan = new Penjualan();

    /** Creates new form popupbarang */
    public pop_up_barang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(530, 400);
        posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth()) / 3;
        int y = (posisi.height - this.getHeight()) /4;
        this.setLocation(x,y);

        tblcari.setAutoCreateColumnsFromModel(false);
        tblcari.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom = tblcari.getColumnCount();
        for(int i = 0;i<kolom;i++){
            TableColumn tc = tblcari.getColumnModel().getColumn(i);
            tc.setPreferredWidth(lebar[i]);
        }
        tabmod = new DefaultTableModel(null,new String[47])
                {
                public boolean  isCellEditable(int rowIndex,int columnIndex ){
                    return false;
                }
            };        
        tblcari.setModel(tabmod);
       batal();
    }
    
    void tableClear(){
	int brs = tabmod.getRowCount();
	for(int i=0;i<brs;i++){
            tabmod.removeRow(0);
        }
    }
        void tableView(){
        tableClear();
        String data[][]=cek.cekTblBarang();
        int i=0;
        while(i<data.length){
            String[] databaris = {data[i][0],data[i][1],data[i][4],data[i][6]};
            tabmod.addRow(databaris);
            i++;    
        }
    }

         void tampil(){
        tableClear();
        String data[][]=cek.CekPopUpBarang(txtcari.getText());
        int i=0;
        while(i<data.length){
            String[] databaris = {data[i][0],data[i][1],data[i][4],data[i][6]};
            tabmod.addRow(databaris);
            i++;    
        }
    }        
        
    void batal(){
     tableView();
        }
 
      public String[]getData(){
        return barang.getDataPopup();           
      }         
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcari = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cari Berdasarkan Nama Barang");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        tblcari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Deskripsi", "Harga"
            }
        ));
        tblcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcariMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcari);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcariMouseClicked
        int row = tblcari.getSelectedRow();
        if(evt.getClickCount()==2){
               barang.setDataPopup(new String[]{
                tabmod.getValueAt(row, 0).toString(),
                tabmod.getValueAt(row, 1).toString(),
                tabmod.getValueAt(row, 2).toString(),
                tabmod.getValueAt(row, 3).toString(), 
            });
           
            //trans_pesan.tjumlahbrg.setVisible(true);
            //trans_pesan.tstok2.setVisible(false);

            dispose();
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_tblcariMouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if(evt.getKeyCode()==10)tampil();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                pop_up_barang dialog = new pop_up_barang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcari;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
