/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import PopUp.pop_up_barang;
import View.FrmJual;
import View.FrmPembelian;
import View.LapKeuntungan;
import View.LapPembelian;
import View.LapPengembalian;
import View.LapPenjualan;
/**
 *
 * @author User
 */
public class laporan extends javax.swing.JPanel {

    /**
     * Creates new form transaksi
     */
    public laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lap_penjualan = new javax.swing.JButton();
        lap_pembelian = new javax.swing.JButton();
        lap_keuntungan = new javax.swing.JButton();
        lap_return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lap_penjualan.setContentAreaFilled(false);
        lap_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_penjualanActionPerformed(evt);
            }
        });
        add(lap_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 260));

        lap_pembelian.setContentAreaFilled(false);
        lap_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_pembelianActionPerformed(evt);
            }
        });
        add(lap_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 230, 260));

        lap_keuntungan.setContentAreaFilled(false);
        lap_keuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_keuntunganActionPerformed(evt);
            }
        });
        add(lap_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 240, 260));

        lap_return.setContentAreaFilled(false);
        lap_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_returnActionPerformed(evt);
            }
        });
        add(lap_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 240, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/laporan.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1013, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void lap_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_penjualanActionPerformed
        LapPenjualan dialog = new LapPenjualan(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_lap_penjualanActionPerformed

    private void lap_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_pembelianActionPerformed
         LapPembelian dialog = new LapPembelian(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_lap_pembelianActionPerformed

    private void lap_keuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_keuntunganActionPerformed
        LapKeuntungan dialog = new LapKeuntungan(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_lap_keuntunganActionPerformed

    private void lap_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_returnActionPerformed
        LapPengembalian dialog = new LapPengembalian(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_lap_returnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lap_keuntungan;
    private javax.swing.JButton lap_pembelian;
    private javax.swing.JButton lap_penjualan;
    private javax.swing.JButton lap_return;
    // End of variables declaration//GEN-END:variables
}
