/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import javax.swing.JPanel;
import View.Dashboard;
import View.FrmJual;
import View.FrmPembelian;
import View.FrmReturn;
import View.LapKeuntungan;
import View.LapPembelian;
import View.LapPenjualan;
/**
 *
 * @author User
 */
public class pnl_dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Barang
     */
    public pnl_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_penjualan = new javax.swing.JButton();
        btn_pengembalian = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_keuntungan = new javax.swing.JButton();
        btn_LapPembelian = new javax.swing.JButton();
        btn_LapPenjualan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_penjualan.setContentAreaFilled(false);
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 20, 220, 250));

        btn_pengembalian.setContentAreaFilled(false);
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });
        add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 20, 220, 250));

        btn_pembelian.setContentAreaFilled(false);
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });
        add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 20, 220, 250));

        btn_keuntungan.setContentAreaFilled(false);
        btn_keuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keuntunganActionPerformed(evt);
            }
        });
        add(btn_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 310, 220, 240));

        btn_LapPembelian.setContentAreaFilled(false);
        btn_LapPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LapPembelianActionPerformed(evt);
            }
        });
        add(btn_LapPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 310, 220, 240));

        btn_LapPenjualan.setContentAreaFilled(false);
        btn_LapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LapPenjualanActionPerformed(evt);
            }
        });
        add(btn_LapPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 310, 220, 240));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dash_panel.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        new FrmJual().setVisible(true);
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        new FrmReturn().setVisible(true);
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
       new FrmPembelian().setVisible(true);
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_keuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keuntunganActionPerformed
       LapKeuntungan dialog = new LapKeuntungan(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btn_keuntunganActionPerformed

    private void btn_LapPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LapPembelianActionPerformed
       LapPembelian dialog = new LapPembelian(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btn_LapPembelianActionPerformed

    private void btn_LapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LapPenjualanActionPerformed
      LapPenjualan dialog = new LapPenjualan(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btn_LapPenjualanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LapPembelian;
    private javax.swing.JButton btn_LapPenjualan;
    private javax.swing.JButton btn_keuntungan;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pengembalian;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
