/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import com.placeholder.PlaceHolder;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */

 

public class supplier extends javax.swing.JPanel {
private Statement stat;
private Connection Con;
private Connection con;
private ResultSet res;
private String t;
private Component rootPane;
int baris;
private PreparedStatement pst;
PlaceHolder holder;

    public supplier(){
        initComponents();
        koneksi();
        tabel();
        holder = new PlaceHolder(txtcari, "Masukkan Nama Supplier");
    }
    
     private void koneksi(){
    try {
    Class.forName("com.mysql.jdbc.Driver");
    con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/penjualanarduino", "root", "");
    stat=(Statement) con.createStatement();
    } catch (ClassNotFoundException | SQLException e) {
    JOptionPane.showMessageDialog(null, e);
    }
    }
     
       private void kosongkan()
       { 
       kd_supplier.setText(""); 
       nama_supplier.setText("");
       kontak.setText("");
       email.setText("");
       alamat.setText("");
        }
       
       private void tabel(){ 
     DefaultTableModel t= new DefaultTableModel();
     t.addColumn("kd_supplier"); 
     t.addColumn("nama_supplier"); 
     t.addColumn("kontak");
     t.addColumn("email"); 
     t.addColumn("alamat"); 
     tabel_supplier.setModel(t); 
     try{ res=stat.executeQuery("select * from supplier order by kd_supplier"); 
     while (res.next()) { 
     t.addRow(new Object[]{ res.getString("kd_supplier"),
     res.getString("nama_supplier"), 
     res.getString("kontak"), 
     res.getString("email"), 
     res.getString("alamat")
     }); 
     }
     }catch (Exception e) { 
     JOptionPane.showMessageDialog(rootPane, e); 
     } 
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kd_supplier = new javax.swing.JTextField();
        nama_supplier = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kontak = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_supplier = new javax.swing.JTable();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JToggleButton();
        btsimpan = new javax.swing.JToggleButton();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 230, 230));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bell Gothic Std Black", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SUPPLIER");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel1.setText("Kode Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        add(kd_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 275, -1));
        add(nama_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 275, -1));

        jLabel2.setText("Nama Supplier");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setText("Kontak");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        add(kontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 275, -1));
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 275, -1));

        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setText("Alamat");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 275, -1));

        tabel_supplier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabel_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Supplier", "Nama Supplier", "Kontak", "Email", "Alamat"
            }
        ));
        tabel_supplier.setGridColor(new java.awt.Color(153, 153, 153));
        tabel_supplier.setSelectionBackground(new java.awt.Color(0, 153, 51));
        tabel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_supplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_supplier);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 559, 210));

        btedit.setText("UPDATE");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        bthapus.setText("DELETE");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        btsimpan.setText("SAVE");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));
        add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 170, 30));

        btncari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 60, 30));

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        try {
            stat.executeUpdate("update supplier set "
                + "kd_supplier='"+kd_supplier.getText()+"',"
                + "nama_supplier='"+nama_supplier.getText()+"',"
                + "kontak='"+kontak.getText()+"',"
                + "email='"+email.getText()+"',"
                + "alamat='"+alamat.getText()+"'"
                + " where " + "kd_supplier='"+kd_supplier.getText()+"'" );
            kosongkan();
            JOptionPane.showMessageDialog(rootPane, "Data berhasil Di update");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
         tabel();
        }     
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        try { 
        stat.executeUpdate("delete from supplier where " 
        + "kd_supplier='"+kd_supplier.getText()
        +"'" ); 
        kosongkan(); 
        JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (SQLException | HeadlessException e) { 
        JOptionPane.showMessageDialog(null, "pesan salah : "+e);
         } finally{
         tabel();
          }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
             try {
            stat.executeUpdate("insert into supplier values (" 
           + "'" + kd_supplier.getText()+"',"
           + "'" + nama_supplier.getText()+"',"
           + "'" + kontak.getText()+"',"
           + "'" + email.getText()+"'," 
           + "'" + alamat.getText()+ "')");
           kosongkan(); 
           JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data"); 
           } catch (SQLException | HeadlessException e) { 
           JOptionPane.showMessageDialog(null, "Perintah Salah : "+e);
           }finally{
                    tabel();       
            } 
    }//GEN-LAST:event_btsimpanActionPerformed

    private void tabel_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_supplierMouseClicked
        baris = tabel_supplier.getSelectedRow();
        kd_supplier.setText(tabel_supplier.getValueAt(baris,0).toString());
        nama_supplier.setText(tabel_supplier.getValueAt(baris,1).toString());
        kontak.setText(tabel_supplier.getValueAt(baris,2).toString());
        email.setText(tabel_supplier.getValueAt(baris,3).toString());
        alamat.setText(tabel_supplier.getValueAt(baris,4).toString());
    }//GEN-LAST:event_tabel_supplierMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        
        DefaultTableModel tabelTampil1 = new DefaultTableModel();
        tabelTampil1.addColumn("kd_supplier");
        tabelTampil1.addColumn("nama_supplier");
        tabelTampil1.addColumn("kontak");
        tabelTampil1.addColumn("email");
        tabelTampil1.addColumn("alamat");
        try{
            koneksi();
            String sql = "Select * from supplier where kd_supplier like '%" + txtcari.getText() + "%'" +
            "or nama_supplier like '%" + txtcari.getText() + "%'";
            pst = con.prepareStatement(sql);
            res = pst.executeQuery();
            while (res.next()) {
                tabelTampil1.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5)
                });
            }
            tabel_supplier.setModel(tabelTampil1);

        }catch (Exception e){

        }
    }//GEN-LAST:event_btncariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tabel();
        kosongkan();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton btedit;
    private javax.swing.JToggleButton bthapus;
    private javax.swing.JButton btncari;
    private javax.swing.JToggleButton btsimpan;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kd_supplier;
    private javax.swing.JTextField kontak;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JTable tabel_supplier;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
   

